### PR TITLE
CDPCAM-71 Add Private Subnets validation with 'Auto-assign public IPs' disabled

### PR DESCRIPTION
**Pull request by anuragpatro**
Signed-off-by: Anurag Patro <anurag.patro@cloudera.com>

Private Subnets required 'Auto-assign public IPs' option to be disabled since we are following a 'fully private' configuration for network architecture. Adding validation and tests for the same. 

tests/validation/infra/test_validate_aws_subnets.py::test_aws_public_subnets_validation_failure PASSED                                                                         [  7%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_public_subnets_suffix_validation_success PASSED                                                                  [ 10%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_public_subnets_suffix_validation_failure PASSED                                                                  [ 14%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_public_subnets_availablity_zone_validation_success PASSED                                                        [ 17%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_public_subnets_availablity_zone_validation_failure PASSED                                                        [ 21%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_public_subnets_route_validation_success PASSED                                                                   [ 25%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_public_subnets_route_validation_failure PASSED                                                                   [ 28%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_public_subnets_range_validation_success PASSED                                                                   [ 32%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_public_subnets_range_validation_failure PASSED                                                                   [ 35%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_public_subnets_tags_validation_success PASSED                                                                    [ 39%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_public_subnets_tags_validation_failure PASSED                                                                    [ 42%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_validation_success PASSED                                                                        [ 46%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_validation_failure PASSED                                                                        [ 50%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_suffix_validation_success PASSED                                                                 [ 53%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_suffix_validation_failure PASSED                                                                 [ 57%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_availablity_zone_validation_success PASSED                                                       [ 60%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_availablity_zone_validation_failure PASSED                                                       [ 64%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_route_validation_success PASSED                                                                  [ 67%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_route_validation_failure PASSED                                                                  [ 71%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_range_validation_success PASSED                                                                  [ 75%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_range_validation_failure PASSED                                                                  [ 78%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_tags_validation_success PASSED                                                                   [ 82%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_tags_validation_failure PASSED                                                                   [ 85%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_auto_assign_ip_validation_success PASSED                                                         [ 89%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_private_subnets_auto_assign_ip_validation_failure PASSED                                                         [ 92%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_vpc_validation_success PASSED                                                                                    [ 96%]
tests/validation/infra/test_validate_aws_subnets.py::test_aws_vpc_validation_failure PASSED                                                                                    [100%]

=====================28 passed in 0.60s ===============================

### CODE REVIEW

**Comment by anuragpatro** [comment]
@mahendra-rk @aakanser @wonderslug 
Please review if the validation seems okay, thanks

**Comment by wonderslug** [comment]
I think the test is probably fine. But we are introducing warnings as well as failures and I think this is a good candidate to be a warning since I don't think it would actually effect of the provisioning of an environment fails or not.

Maybe we can just hold onto this till we get warning in in the next week or so and rebase and update it then?

**Comment by wonderslug** [comment]
@anuragpatro Ok Warn and the new issues system is now in place in dev.  If you can please rebase against dev and see the other validations for how the issues are being presented now with the fail and the warn functions.  In order to get your Issue which you add to the issue_templates.yml file, you need to run the scripts/update_issue_templates.py.  This will add a const for the issue in the issues.py to use for references.

**Comment by anuragpatro** [comment]
Made the necessary changes, please review. 
One of your commit seems to be missing the sign-off, that's raising an error, if that can be forced through (if maintainers have that ability), should be fine else please tell me how to bypass that.

**Comment by wonderslug** [comment]
Looks like a couple of minor lint and isort issues.  If you can please fix we can get these in. 

You can check these locally before you commit by doing a **pre-commit run --all** inside the dev container terminal.

Other then that looking good.  Not sure why there is the DCO issue.

**Review by mahendra-rk — APPROVED** [review]
LGTM!

**Comment by mahendra-rk** [comment]
Please run lint and add necessary fixes

**Comment by wonderslug** [comment]
Thanks for the validation!

**Pull request merged**
